---
# -------------------------------------------------------------------------------------------------
- name: "Vultr infrastructure destroy playbook"
  hosts: "localhost"
  gather_facts: false
  vars:
    "override_region": ""
  tasks:
    # ---------------------------------------------------------------------------------------------
    - name: "Override deployment region if variable is set"
      ansible.builtin.set_fact:
        "virtual_region": "{{ override_region }}"
        "bare_metal_region": "{{ override_region }}"
      when: "override_region"
    # ---------------------------------------------------------------------------------------------
    - name: "Include destroy infrastructure role"
      ansible.builtin.include_role:
        name: "destroy_infrastructure"
